# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "dailymile-ruby"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["lostinpatterns"]
  s.date = "2012-04-11"
  s.description = "This gem wraps the dailymile API that's available at http://www.dailymile.com/api"
  s.email = "blweiner@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "dailymile-ruby.gemspec",
    "lib/dailymile.rb",
    "lib/dailymile/client.rb",
    "lib/dailymile/connection.rb",
    "lib/dailymile/connection/token.rb",
    "test/helper.rb",
    "test/test_dailymile-ruby.rb"
  ]
  s.homepage = "http://github.com/dailymile/dailymile-ruby"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "dailymile ruby client"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<faraday>, ["~> 1.0"])
      s.add_runtime_dependency(%q<json_pure>, [">= 0"])
      s.add_runtime_dependency(%q<oauth2>, ["= 0.5.2"])
    else
      s.add_dependency(%q<faraday>, ["~> 1.0"])
      s.add_dependency(%q<json_pure>, [">= 0"])
      s.add_dependency(%q<oauth2>, ["= 0.5.2"])
    end
  else
    s.add_dependency(%q<faraday>, ["~> 1.0"])
    s.add_dependency(%q<json_pure>, [">= 0"])
    s.add_dependency(%q<oauth2>, ["= 0.5.2"])
  end
end

